# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#                                                                                                                     #
#                                                  Bow Training                                                       #
#                                                Configuration zone                                                    #
#                                              Developed by WhiteFox                                                  #
#                                   Github.com : https://github.com/whitefox2232                                      #
#                                                                                                                     #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

timer: 60
auto-start: false
targets: 1
area:
  point1:
  point2: